### ISSUE TITLE
Use pipe functionality of functools-extra package?

### ISSUE THREAD

**Issue by dennis-rall** [KlausH09/kothon#1]
Hey @KlausH09,

check out the `pipe` functionality of the [functools-extra](https://pypi.org/project/functools-extra/) package.
With it you can get rid of the `Seq` wrapper class and all the wrapper functions. Just use the operators directly.
So
```python
from kothon import Seq, filter_not_none

seq = Seq([1, None, 2, None, None])

result = seq \
  .filter_not_none() \
  .to_list()

```
transforms to
```python
from functools_extra import pipe
from kothon import filter_not_none

result = pipe(
    [1, None, 2, None, None],
    filter_not_none,
    list,
)

```

If the value is typed properly, also the types are inferred correctly. So in this case
```python
from functools_extra import pipe
from kothon import filter_not_none

seq: list[int | None] = [1, None, 2, None, None]

result = pipe(
    seq,
    filter_not_none,
    list,
)
```

`result` is of type `list[int]`.

Also you don't need the extra `\` chars for proper formatting.

**Comment by klahap** [comment]
Hey @dennisrall,

first off, I want to express my gratitude for your excellent suggestion regarding the use of the pipe functionality from the [functools-extra](https://pypi.org/project/functools-extra/) package. It's a clean and elegant approach that certainly enhances the readability and simplicity of the code.

However, I encountered a bit of a snag when considering this for integration into kothon. One of the core principles we adhere to in kothon is robust type safety, ensuring that our codebase is as reliable and error-free as possible. Upon reviewing functools-extra, I noticed that it doesn't provide type stub files (.pyi), which are crucial for static type checking and thus integral to maintaining the level of type safety we aim for in kothon.

That being said, the concept of the pipe function really resonated with me, and I see great value in its application. So much so, that I decided to implement a version of the pipe function directly within kothon. I'm excited to share that this feature has been incorporated into the latest version of our library, kothon 0.3.1. This ensures that we can enjoy the benefits of the pipe functionality while still adhering to our stringent requirements for type safety. (see [readme#quick-start](https://github.com/KlausH09/kothon/tree/0.3.1?tab=readme-ov-file#quick-start))

I truly appreciate your contribution to the discussion and for prompting an enhancement to kothon. Your insight is invaluable, and I look forward to seeing more interactions and suggestions from our community members like you.
